apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ingest
  labels:
    component: elasticsearch
    role: ingest
spec:
  selector:
    component: elasticsearch
    role: ingest
  ports:
  - name: http3
    port: 9200
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-ingest
  labels:
    component: elasticsearch
    role: ingest
spec:
  replicas: 2
  template:
    metadata:
      labels:
        component: elasticsearch
        role: ingest
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - {key: role, operator: In, values: [ingest]}
              topologyKey: "kubernetes.io/hostname"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - {key: es-master, operator: In, values: ["yes"]}
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-ingest
        #image: trow.kube-public:31000/kp/kp-elasticsearch:7.3.0
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
        #lifecycle:
        #  postStart:
        #    exec:
        #      command: ["/bin/sh", "-c", "/usr/share/elasticsearch/bin/elasticsearch-certutil cert --ca-cert /tmp/tls/tls.crt --ca-key /tmp/tls/tls.key --ca-pass \"\" --pass \"\" --out /tmp/es-certs.p12 && chown 1000:1000 /tmp/es-certs.p12"]
        env:
        #- name: NAMESPACE
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: metadata.namespace
        #- name: node.name
          #value: 
          #valueFrom:
          #  fieldRef:
          #    fieldPath: metadata.name
        #- name: CLUSTER_NAME
        #  value: kp-sandbox-es
        #- name: NODE_MASTER
        #  value: "false"
        #- name: NODE_DATA
        #  value: "false"
        - name: node.ingest
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms2048m -Xmx2048m
        #- name: "ES_PLUGINS_INSTALL"
        #  value: "mapper-size"
        #- name: NETWORK_HOST
        #  value: _eth0:ipv4_,_lo_
        - name: ES_PATH_CONF
          value: "/usr/share/elasticsearch/config"
        #- name: PROCESSORS
        #  valueFrom:
        #    resourceFieldRef:
        #      resource: limits.cpu
       # resources:
       #   requests:
       #    cpu: 1
       #   limits:
       #     cpu: 2
        ports:
        - containerPort: 9200
          name: http3
        - containerPort: 9300
          name: transport3
        livenessProbe:
          tcpSocket:
            port: transport3
          initialDelaySeconds: 20
          periodSeconds: 10
        #readinessProbe:
        #  httpGet:
        #    path: /_cluster/health
        #    port: http3
            #httpHeaders:
            #  - name: Authorization
            #    value: "Basic ZWxhc3RpYzprcCNwYXNz"
       #   initialDelaySeconds: 20
       #   timeoutSeconds: 5
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        #- name: secret-volume
        #  mountPath: /tmp/tls
      volumes:
          - emptyDir:
              medium: ""
            name: storage
          - name: config
            configMap:
              name: es-config
          #- name: secret-volume
          #  secret:
          #    secretName: tls-secret
