apiVersion: v1
kind: Service
metadata:
  name: ed-a
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master-a
  ports:
  - name: transport1
    port: 9300
    protocol: TCP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-master-a
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    matchLabels:
      component: elasticsearch
      role: master-a
  serviceName: ed-a
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master-a
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - {key: role, operator: In, values: [master]}
              topologyKey: "kubernetes.io/hostname"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - {key: es-master, operator: In, values: ["yes"]}
              - {key: zone, operator: In, values: ["a"]}
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-master-a
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
        securityContext:
          privileged: true
        env:
        - name: node.name
          value: "ed-a"
        - name: node.master
          value: "true"
        - name: ES_PATH_CONF
          value: "/usr/share/elasticsearch/config"
        resources:
          requests:
            cpu: 0.5
          limits:
            cpu: 2
        ports:
        - containerPort: 9300
          name: transport1
        livenessProbe:
          tcpSocket:
            port: transport1
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
        - name: config
          configMap:
            name: es-config
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: "local-path"
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 5Gi
